### ISSUE TITLE
YAML comments are stripped

### ISSUE THREAD

**Issue by bbrks** [thim81/openapi-format#44]
I have no idea if this is intentional, or just a difficult problem to solve, but comments are stripped from YAML OpenAPI specs.
This becomes a little bit problematic when the comments are meaningful to the openapi writer and help maintainability. 

E.g:
```yaml
# asdf
info:
  title: title
  description: description
  version: "3.1.0" # comment
```

Becomes

```yaml
info:
  title: title
  description: description
  version: 3.1.0
```

**Comment by thim81** [comment]
@bbrks Sadly enough, there is no way to keep the comments.
We are using a YAML parsing library and all YAML libraries strip the comments by default as soon as they serialise the content of the YAML file.
openapi-format uses https://github.com/stoplightio/yaml for parsing the YAML file, so perhaps you can open an issue to see if they have a solution for the comments?

If you find a manner, please let me know, since I struggle with the comments being removed as well.

A possible work-around is that you format the file and write the formatted file next the original file and do a diff of both files.

**Comment by a-waider** [comment]
I've experienced a similar issue. An example for a request body with an epmty object gets stripped away.

E.g. 
``` yaml
example:
  default
    key1: "value1"
    key: {}
```
becomes
``` yaml
example:
  default:
    key1: "value1"
```

Is this related to the parsing library used in openapi-format? Do you have any suggestions how to preserve the empty object?

**Comment by thim81** [comment]
hi @a-waider 

This seems like a another issue, but I would have to investigate it.
Could you create a separate github issue for this, that way I can leave the original item open and tackle this in the new issue?

**Comment by a-waider** [comment]
> hi @a-waider
> 
> This seems like a another issue, but I would have to investigate it. Could you create a separate github issue for this, that way I can leave the original item open and tackle this in the new issue?

Just created a new issue #72 :)

**Comment by thim81** [comment]
Update: Stoplight YAML-ast-parser introduced the option to preserve comments on YAML docs, https://github.com/stoplightio/yaml-ast-parser/pull/6

Will need some more investigation

**Comment by thim81** [comment]
hi @bbrks 

We just [release v1.23.0](https://github.com/thim81/openapi-format/releases/tag/v1.23.0) which provides the option` --keepComments` which keep the YAML comments in a file.

Closing this issue.
If you're still experiencing problems, please feel free to reopen this issue or create a new one. Thanks for taking the time to report it!
