### ISSUE TITLE
Issues with cookie parameters being excluded from formatted document

### ISSUE THREAD

**Issue by bradworsfold-workday** [thim81/openapi-format#61]
Seems that components->parameters->cookies are not supported.  In fact, if you add a parameter with in: cookie, the parameter is not included in the output.  That is a bit of a head scratcher.

Supported in version 3.0.3
https://swagger.io/docs/specification/describing-parameters/#cookie-parameters

`    
"components": {
    "parameters": {
        "JSESSIONID": {
          "name": "JSESSIONID",
          "in": "cookie",
          "required": false,
          "schema": {
              "type": "string"
          }
      }
    }
}
`

**Comment by bradworsfold-workday** [comment]
Looks to be an issue in this block just ignoring cookie based parameters.  Would be simple to add.
https://github.com/thim81/openapi-format/blob/8a2181bcb75126fa9e88692d7e42d03d885cba48/openapi-format.js#L616-L640

**Comment by thim81** [comment]
@bradworsfold-workday Thanks for reporting the issue.

I'll have a look and it should be rather straightforward to add the cookie parameters.

Did I understand your  use-case correct?
You want to format the OpenAPI document, including the cookie parameters, while instead of being nicely ordered, they are being removed from the formatted result?

**Comment by bradworsfold-workday** [comment]
Correct.  I have a solution for this.  I will fork and push it up for you to take a look at.

**Comment by bradworsfold-workday** [comment]
https://github.com/thim81/openapi-format/pull/62

**Comment by bradworsfold-workday** [comment]
@thim81 is it possible to review the PR and get this in?  Thanks. 🙇

**Comment by thim81** [comment]
Hi @bradworsfold-workday

I m this week not near a laptop or pc, but my plan was to review the PR next week and potentially release it next week.

**Comment by thim81** [comment]
hi @bradworsfold-workday 

I had the time to review and merge your PR.
Thanks for taking the time to also update the readme and extend the test.

I'm going to close this issue, since openapi-format version 1.11.0 was just released, which contains your PR for adding support for parameters in Cookies ( #62).
